# Site settings
title: "nnwb"
description: > 
  blog

author: nnwb
email: jupiterjaz@gmail.com
twitter_username:
github_username: 
instagram_username:

baseurl: "/nnwb.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

google_analytics_id: 
disqus_id: "nnwb"

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

