# Site settings
title: "Paper Jekyll Theme"
description: > 
  nnwb

author: Hyunsoo Shin
email: jupiterjaz@gmail.com
twitter_username:
github_username: nnwb

baseurl: "/nnwb.github.io" # the subpath of your site, e.g. /blog
url: "https://nnwb.github.io" # the base hostname & protocol for your site

google_analytics_id: UA-1111111111-1
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

